# Generated by Django 3.1.2 on 2020-10-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purchase_price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('stock_qty', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inv_app.category')),
            ],
        ),
    ]
