# Generated by Django 3.1.2 on 2020-10-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oreder_qty',
            field=models.IntegerField(default=0),
        ),
    ]
